#!/usr/bin/env node
/**
 * Sanctioned atomic version bump.
 *
 * The project version is a single source of truth fanned out across five
 * release surfaces that MUST move together on every bump. A human remembering
 * each one is how a release drifts (a root manifest bumped while the committed
 * `.claude` tree and lockfile stayed on the prior prerelease). This script sets
 * all five to one target in lockstep, regenerates the derived artifacts, stages
 * exactly the enumerated release files, and fails closed on any residual drift.
 *
 * Surfaces:
 *   1. root `package.json` `version`
 *   2. `packages/core/package.json` `version`
 *   3. root `@dev-loops/core` dependency range (`^<version>`)
 *   4. `bun.lock` (regenerated by `bun install --lockfile-only`, proven with
 *      `bun install --frozen-lockfile`)
 *   5. the generated `.claude` tree — `.claude/.claude-plugin/plugin.json`
 *      `version` and every pinned `npx dev-loops@<version>` call-site
 *      (produced by `scripts/claude/generate-claude-assets.mjs`)
 *
 * Bump-only: it never commits, tags, pushes, or publishes. Commit + tag + push
 * and the stable-release approval gate remain operator/runbook-owned.
 *
 * Idempotent: re-running with the same target is a no-op. The target may carry
 * any prerelease token (`1.0.2-slim.0`, `1.0.0-rc.7`, …); surfaces are compared
 * as full version tokens (including the prerelease suffix), matching the
 * release-time lockstep guard.
 *
 * Usage:
 *   node scripts/release/bump-version.mjs <target-version> [--repo-root <path>] [--jq <filter>] [--silent]
 * Exits 0 on full lockstep, 1 on drift/failure, 2 on usage/parse error.
 */
import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { isDirectCliRun } from "../lib/direct-run.mjs";
import { emitResult } from "../lib/jq-output.mjs";
import { extractFullVersion } from "./assert-core-dependency-version.mjs";

const CORE_DEP = "@dev-loops/core";
// A bare full semver token, optionally with a prerelease suffix. Build metadata
// (`+build`) is rejected: the lockstep guards compare the full version token and
// nothing on the release surfaces carries a build suffix.
const TARGET_RE = /^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/;

function readJson(file) {
  return JSON.parse(readFileSync(file, "utf8"));
}

// Write JSON in the repo's canonical shape: 2-space indent, trailing newline.
function writeJson(file, value) {
  writeFileSync(file, `${JSON.stringify(value, null, 2)}\n`);
}

function run(command, args, cwd) {
  // Route the subprocess's own stdout to stderr (fd 2) so this script's stdout
  // stays a single clean JSON summary that --jq/--silent can consume.
  const result = spawnSync(command, args, { cwd, stdio: ["ignore", 2, 2], encoding: "utf8" });
  if (result.error) throw new Error(`${command} ${args.join(" ")} failed to start: ${result.error.message}`);
  if (result.status !== 0) throw new Error(`${command} ${args.join(" ")} exited ${result.status}`);
}

/**
 * Set the three hand-edited surfaces (root version, root core-dependency range,
 * core package version). Returns the enumerated file paths touched.
 * @returns {string[]}
 */
export function writeManifestSurfaces(repoRoot, version) {
  const rootPath = path.join(repoRoot, "package.json");
  const corePath = path.join(repoRoot, "packages/core/package.json");

  const root = readJson(rootPath);
  root.version = version;
  if (!root.dependencies || !(CORE_DEP in root.dependencies)) {
    throw new Error(`root package.json has no ${CORE_DEP} dependency to bump`);
  }
  root.dependencies[CORE_DEP] = `^${version}`;
  writeJson(rootPath, root);

  const core = readJson(corePath);
  core.version = version;
  writeJson(corePath, core);

  return [rootPath, corePath];
}

/**
 * Read every release surface back and confirm it carries the target full token.
 * Pure inspection over on-disk state; returns per-surface { name, value, ok }.
 * @returns {{name:string,value:string,ok:boolean}[]}
 */
export function inspectSurfaces(repoRoot, version) {
  const root = readJson(path.join(repoRoot, "package.json"));
  const core = readJson(path.join(repoRoot, "packages/core/package.json"));
  const manifest = readJson(path.join(repoRoot, ".claude/.claude-plugin/plugin.json"));
  const lock = readFileSync(path.join(repoRoot, "bun.lock"), "utf8");

  // bun.lock is JSONC (trailing commas); avoid a full parse — the lockstep guard
  // already validates it structurally. Confirm the full token appears for both
  // the workspace entry and the dependency spec.
  const lockOk =
    lock.includes(`"version": "${version}"`) && lock.includes(`"${CORE_DEP}": "^${version}"`);

  // Every pinned npx call-site in the generated tree must carry the target.
  const claudeDir = path.join(repoRoot, ".claude");
  // Positive version charset (digits, dots, hyphen, prerelease/build alnum) so a
  // call-site with trailing punctuation (`)`, `,`) does not capture it into the pin.
  const grep = spawnSync("grep", ["-rhoE", "dev-loops@[0-9][0-9A-Za-z.+-]*", claudeDir], { encoding: "utf8" });
  const pins = (grep.stdout || "").split("\n").filter(Boolean);
  const pinsOk = pins.length > 0 && pins.every((p) => p === `dev-loops@${version}`);

  return [
    { name: "root package.json version", value: root.version, ok: root.version === version },
    { name: "packages/core package.json version", value: core.version, ok: core.version === version },
    {
      name: "root @dev-loops/core range",
      value: root.dependencies?.[CORE_DEP],
      ok: extractFullVersion(String(root.dependencies?.[CORE_DEP] ?? "")) === version,
    },
    { name: "bun.lock lockstep", value: lockOk ? "lockstep" : "drift", ok: lockOk },
    { name: "plugin.json version", value: manifest.version, ok: manifest.version === version },
    {
      name: "pinned npx call-sites",
      value: [...new Set(pins)].join(",") || "(none found)",
      ok: pinsOk,
    },
  ];
}

// `run` is injectable so the orchestration (surface writes → regen → guards →
// staging → drift-throw) is testable without a resolvable @dev-loops/core or a
// real bun install; production passes the default module `run`.
export function bumpVersion({ repoRoot, version, stage = true, run: runChild = run }) {
  const full = extractFullVersion(version);
  if (full !== version) {
    // extractFullVersion tolerates leading range operators / `v`; the target
    // must be a bare full token so surfaces carry exactly what was requested.
    throw new Error(`target "${version}" is not a bare full version token (parsed as "${full}")`);
  }

  // Surfaces 1-3: hand-edited manifests.
  const manifestPaths = writeManifestSurfaces(repoRoot, version);

  // Surface 4: regenerate the lockfile from the bumped manifests.
  runChild("bun", ["install", "--lockfile-only"], repoRoot);

  // Surface 5: regenerate the .claude tree (stamps plugin.json version + npx pins
  // from the now-bumped root package.json version).
  runChild("node", [path.join(repoRoot, "scripts/claude/generate-claude-assets.mjs")], repoRoot);

  // Fail-closed drift guards over the regenerated surfaces.
  runChild("bun", ["install", "--frozen-lockfile"], repoRoot); // proves bun.lock is in lockstep
  runChild("node", [
    path.join(repoRoot, "scripts/release/assert-core-dependency-version.mjs"),
    "--release-version",
    version,
  ], repoRoot);
  runChild("node", [path.join(repoRoot, "scripts/claude/generate-claude-assets.mjs"), "--check"], repoRoot);

  // Direct surface inspection: a clear per-surface drift report on top of the guards.
  const surfaces = inspectSurfaces(repoRoot, version);
  const drifted = surfaces.filter((s) => !s.ok);
  if (drifted.length > 0) {
    throw new Error(
      `residual drift after bump to ${version}:\n` +
        drifted.map((s) => `  - ${s.name}: ${s.value}`).join("\n"),
    );
  }

  // Stage only the enumerated release paths — never `git add -A` / `git add .`.
  const stagedPaths = [...manifestPaths, path.join(repoRoot, "bun.lock"), path.join(repoRoot, ".claude")];
  if (stage) runChild("git", ["add", "--", ...stagedPaths], repoRoot);

  return { ok: true, version, surfaces, staged: stagedPaths };
}

function parseArgs(argv) {
  const args = [...argv];
  let repoRoot = null;
  let jq;
  let silent = false;
  const positional = [];
  for (let i = 0; i < args.length; i += 1) {
    const arg = args[i];
    if (arg === "--repo-root") {
      repoRoot = args[++i];
    } else if (arg === "--jq") {
      jq = args[++i];
    } else if (arg === "--silent" || arg === "-s") {
      silent = true;
    } else {
      positional.push(arg);
    }
  }
  return { version: positional[0], repoRoot, jq, silent };
}

function main(argv) {
  const { version, repoRoot: repoRootArg, jq, silent } = parseArgs(argv);
  if (!version) {
    process.stderr.write("Usage: node scripts/release/bump-version.mjs <target-version> [--repo-root <path>] [--jq <filter>] [--silent]\n");
    process.exit(2);
  }
  if (!TARGET_RE.test(version)) {
    process.stderr.write(`Invalid target version "${version}": expected a bare semver token (e.g. 1.0.2 or 1.0.2-slim.0).\n`);
    process.exit(2);
  }
  const repoRoot = path.resolve(
    repoRootArg ?? path.join(path.dirname(fileURLToPath(import.meta.url)), "../.."),
  );
  try {
    const result = bumpVersion({ repoRoot, version });
    process.exit(emitResult(result, { jq, silent }));
  } catch (error) {
    process.stderr.write(`[bump-version] ${error.message}\n`);
    process.exit(1);
  }
}

if (isDirectCliRun(import.meta.url)) {
  main(process.argv.slice(2));
}
